### ISSUE TITLE
I was just about to write a PR for this with the Byte("|") errors, but it's fixed.

### ISSUE THREAD

**Issue by hpux735** [itssofluffy/NanoMessage#1]
So, you you mind tagging the release? :)

**Comment by itssofluffy** [comment]
I've just tagged the release as it seems to compile fine under MacOS now but as your probably aware the unit tests fail because of the async nature that XCTest cases are executed (only just found this out by using travis). I'll fix this later on today.

**Comment by hpux735** [comment]
Awesome!  That works perfectly!  Thanks!!
